[tool.poetry]
name = "crudapi"
version = "0.1.0"
description = ""
authors = ["Mateo Harfuch <mharfuch@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.61.1"
SQLAlchemy = "^1.3.20"
pydantic-sqlalchemy = "^0.0.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
requests = "^2.24.0"
pre-commit = "^2.8.2"
black = "^20.8b1"
uvicorn = "^0.12.2"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
